export const settingDefaults: Record<string, unknown> = {
  "general.theme": "Dark",
  "general.language": "English",

  // Language display name → locale code mapping (used by AppSettingsProvider)
  // "English" → "en", "Português (BR)" → "pt-BR", "Español" → "es", "Français" → "fr", "Deutsch" → "de"
  "general.startupBehavior": "Resume last session",
  "general.defaultLandingScreen": "Home",
  "general.confirmBeforeClose": true,
  "general.autoSaveSessions": true,

  "editor.fontSize": 13,
  "editor.fontFamily": "JetBrains Mono",
  "editor.tabWidth": "2",
  "editor.wordWrap": true,
  "editor.lineNumbers": true,
  "editor.minimap": false,
  "editor.diffView": "Inline",
  "editor.showWhitespaceChanges": false,
  "editor.contextLines": 3,

  "terminal.defaultShell": "zsh",
  "terminal.shellArguments": "--login",
  "terminal.fontFamily": "JetBrains Mono",
  "terminal.fontSize": 13,
  "terminal.cursorStyle": "Block",
  "terminal.ansiColorTheme": "Amoena Dark",
  "terminal.scrollbackLines": 10000,
  "terminal.copyOnSelect": false,
  "terminal.rightClickPaste": false,

  "session.defaultModel": "Claude 4 Sonnet",
  "session.defaultReasoningMode": "Auto",
  "session.defaultReasoningDepth": "High",
  "session.defaultPermissionPreset": "Default (ask before risky)",
  "session.defaultWorkTarget": "Local project",
  "session.autoIncludeOpenFiles": false,
  "session.includeIdeContext": true,
  "session.maxContextTokens": 32000,

  "memory.observationRetention": "30 days",
  "memory.autoSummarizeSessions": true,
  "memory.summaryGenerationModel": "Same as session",
  "memory.autoInjectRelevantMemory": true,
  "memory.maxInjectedTokens": 4000,
  "memory.injectionStrategy": "Hybrid",

  "permissions.defaultApprovalMode": "Ask before risky actions",
  "permissions.rememberApprovalChoices": true,
  "permissions.fileDeletion": "Always ask",
  "permissions.terminalExecution": "Always ask",
  "permissions.gitOperations": "Always ask",
  "permissions.networkRequests": "Always ask",

  "privacy.usageAnalytics": true,
  "privacy.crashReporting": true,
  "privacy.sensitiveContentHandling": "Redact before sending",
  "privacy.dataRetention": "30 days",
  "privacy.autoRedactSecrets": true,

  "advanced.developerMode": false,
  "advanced.runtimeDiagnostics": false,
  "advanced.verboseLogging": false,
  "advanced.experimentalFeatures": false,
  "advanced.canvasRendering": false,
  "advanced.streamingResponses": true,
  "advanced.runtimePort": 3847,
  "advanced.maxConcurrentAgents": 4,
  "advanced.requestTimeout": "60s",

  "notifications.showToast": true,
  "notifications.toastDuration": "5 seconds",
  "notifications.toastPosition": "Bottom right",
  "notifications.criticalAlerts": true,
  "notifications.backgroundTaskCompletion": true,
  "notifications.soundEffects": false,
  "notifications.remoteApprovalNotifications": true,
  "notifications.mobilePushNotifications": false,

  "themes.accentColor": "Magenta",
  "themes.uiDensity": "Comfortable",

  "keybindings.preset": "Default",

  "workspace.defaultWorktreeLocation": "~/.amoena/worktrees",
  "workspace.autoCreateWorktree": false,
  "workspace.cloneStrategy": "Full clone",
  "workspace.defaultBranch": "main",
  "workspace.mergeReviewBehavior": "Always require review",
  "workspace.autoCleanup": false,
  "workspace.cleanupAfterDays": 7,
};
