import { vi } from "vitest";

export function createMockClient() {
  return {
    request: vi.fn(),
    sessionEventsUrl: vi.fn(() => "http://localhost/events/session"),
    globalEventsUrl: vi.fn(() => "http://localhost/events/global"),
    listSessions: vi.fn().mockResolvedValue([]),
    deleteSession: vi.fn().mockResolvedValue(undefined),
    listSessionMessages: vi.fn().mockResolvedValue([]),
    getSessionTranscript: vi.fn().mockResolvedValue([]),
    createSessionMessage: vi.fn().mockResolvedValue({ id: "msg-1", role: "user", content: "", attachments: [], createdAt: "" }),
    setSessionAutopilot: vi.fn().mockResolvedValue({}),
    listSessionAgents: vi.fn().mockResolvedValue([]),
    getSessionMemory: vi.fn().mockResolvedValue({ summary: null, tokenBudget: { total: 0, l0: 0, l1: 0, l2: 0 }, entries: [] }),
    createPairingIntent: vi.fn().mockResolvedValue({}),
    completePairing: vi.fn().mockResolvedValue({
      tokenType: "Bearer",
      accessToken: "test-access",
      refreshToken: "test-refresh",
      deviceId: "device-1",
      scopes: [],
      baseUrl: "http://127.0.0.1:47821",
      serverUrl: "http://127.0.0.1:47821",
    }),
    refreshRemoteAuth: vi.fn().mockResolvedValue({}),
    remoteDeviceMe: vi.fn().mockResolvedValue({ deviceId: "device-1", scopes: [] }),
    createTerminalSession: vi.fn().mockResolvedValue({ terminalSessionId: "term-1" }),
    sendTerminalInput: vi.fn().mockResolvedValue(undefined),
    resizeTerminalSession: vi.fn().mockResolvedValue(undefined),
    listTerminalEvents: vi.fn().mockResolvedValue([]),
    resolveRemotePermission: vi.fn().mockResolvedValue(undefined),
    listHooks: vi.fn().mockResolvedValue([]),
    registerHook: vi.fn().mockResolvedValue({}),
    deleteHook: vi.fn().mockResolvedValue(undefined),
    fireHook: vi.fn().mockResolvedValue([]),
    listWorkspaces: vi.fn().mockResolvedValue([]),
    createWorkspace: vi.fn().mockResolvedValue({}),
    inspectWorkspace: vi.fn().mockResolvedValue({}),
    archiveWorkspace: vi.fn().mockResolvedValue(undefined),
    destroyWorkspace: vi.fn().mockResolvedValue(undefined),
    reviewWorkspace: vi.fn().mockResolvedValue({}),
    listQueueMessages: vi.fn().mockResolvedValue([]),
    enqueueMessage: vi.fn().mockResolvedValue({}),
    editQueueMessage: vi.fn().mockResolvedValue({}),
    removeQueueMessage: vi.fn().mockResolvedValue(undefined),
    reorderQueue: vi.fn().mockResolvedValue(undefined),
    flushQueue: vi.fn().mockResolvedValue(undefined),
    listTasks: vi.fn().mockResolvedValue([]),
    createTask: vi.fn().mockResolvedValue({}),
    updateTask: vi.fn().mockResolvedValue({}),
    deleteTask: vi.fn().mockResolvedValue(undefined),
    reorderTasks: vi.fn().mockResolvedValue(undefined),
    listExtensions: vi.fn().mockResolvedValue([]),
    installExtension: vi.fn().mockResolvedValue({}),
    uninstallExtension: vi.fn().mockResolvedValue(undefined),
    toggleExtension: vi.fn().mockResolvedValue(undefined),
    getExtensionContributions: vi.fn().mockResolvedValue({ commands: [], menuItems: [], panels: [], settings: [], hooks: [], tools: [], providers: [] }),
    installPlugin: vi.fn().mockResolvedValue({}),
    uninstallPlugin: vi.fn().mockResolvedValue(undefined),
    executePlugin: vi.fn().mockResolvedValue({}),
    pluginHealth: vi.fn().mockResolvedValue({ pluginId: "", status: "healthy" }),
    resolvePermission: vi.fn().mockResolvedValue(undefined),
  };
}

export type MockClient = ReturnType<typeof createMockClient>;
