/**
 * Build script — generates platform-specific token output files.
 * Run via: bun run build:tokens
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { buildDesignTokensJSON } from './build-json';
import { buildNativeTokens } from './build-native';
import { buildWebCSS } from './build-web';
import { amoenaTokens } from './lunaria-theme';

const distDir = join(import.meta.dir, '..', 'dist');
mkdirSync(distDir, { recursive: true });

// CSS custom properties (for Tailwind / web consumption)
writeFileSync(join(distDir, 'tokens.css'), buildWebCSS(amoenaTokens));

// Flat JS/TS object (for React Native)
const nativeTokens = buildNativeTokens(amoenaTokens);
const nativeContent = [
  '// Auto-generated by @lunaria/tokens — do not edit',
  '',
  `export const tokens = ${JSON.stringify(nativeTokens, null, 2)} as const;`,
  '',
  'export type TokenKey = keyof typeof tokens;',
  '',
].join('\n');
writeFileSync(join(distDir, 'tokens.native.ts'), nativeContent);

// Design Tokens Community Group JSON (for Figma / design tools)
const dtcg = buildDesignTokensJSON(amoenaTokens);
writeFileSync(join(distDir, 'tokens.json'), JSON.stringify(dtcg, null, 2) + '\n');

console.log('✓ dist/tokens.css');
console.log('✓ dist/tokens.native.ts');
console.log('✓ dist/tokens.json');
