import type { RunReport } from "./run-reporter";
import { renderMarkdown } from "./run-reporter";
import { scrubReport } from "./secret-scrubber";

export type ExportFormat = "html" | "markdown" | "json";

export interface ExportOptions {
	/** Format to export */
	format: ExportFormat;
	/** Whether to scrub secrets before export (default: true) */
	scrubSecrets?: boolean;
	/** Include raw JSON in HTML export (default: false) */
	includeRawJson?: boolean;
	/** Custom title override */
	title?: string;
	/** Whether to include the Amoena branding footer (default: true) */
	includeBranding?: boolean;
}

export interface ExportResult {
	/** The exported content as a string */
	content: string;
	/** MIME type for the content */
	mimeType: string;
	/** Suggested filename */
	filename: string;
	/** Number of secrets scrubbed (0 if scrubbing disabled) */
	secretsRedacted: number;
}

function getDate(): string {
	return new Date().toISOString().slice(0, 10);
}

function generateFilename(report: RunReport, format: ExportFormat): string {
	const id8 = report.goalId.slice(0, 8);
	const date = getDate();
	return `amoena-report-${id8}-${date}.${format}`;
}

function escapeHtml(str: string): string {
	return str
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
		.replace(/'/g, "&#39;");
}

function formatDurationHtml(ms: number | null): string {
	if (ms == null) return "—";
	const totalSeconds = Math.floor(ms / 1000);
	if (totalSeconds < 60) return `${totalSeconds}s`;
	const minutes = Math.floor(totalSeconds / 60);
	const seconds = totalSeconds % 60;
	return `${minutes}m ${seconds}s`;
}

function formatCostHtml(usd: number | null): string {
	if (usd == null) return "—";
	return `$${usd.toFixed(4)} USD`;
}

function statusClass(status: string): string {
	if (status === "completed") return "status-completed";
	if (status === "failed" || status === "cancelled") return "status-failed";
	if (status === "partial_failure") return "status-partial";
	return "";
}

function agentClass(agentType: string | null): string {
	if (!agentType) return "";
	if (agentType.includes("claude")) return "agent-claude";
	if (agentType.includes("codex")) return "agent-codex";
	if (agentType.includes("gemini")) return "agent-gemini";
	return "";
}

function exportHtml(report: RunReport, options: ExportOptions): string {
	const title = options.title ?? `Mission Control Report: ${report.goalDescription}`;
	const timestamp = new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";
	const tasks = report.taskBreakdown;
	const completed = tasks.filter((t) => t.status === "completed").length;
	const failed = tasks.filter((t) => t.status === "failed").length;

	const rows = tasks
		.map(
			(t) => `
      <tr class="${agentClass(t.agentType)}">
        <td>${escapeHtml(t.description)}</td>
        <td>${escapeHtml(t.taskType)}</td>
        <td><span class="${statusClass(t.status)}">${t.status}</span></td>
        <td>${escapeHtml(t.agentType ?? "—")}</td>
        <td>${formatDurationHtml(t.durationMs)}</td>
        <td>${formatCostHtml(t.costUsd)}</td>
        ${t.errorMessage ? `<td>${escapeHtml(t.errorMessage)}</td>` : "<td>—</td>"}
      </tr>`,
		)
		.join("");

	const agentRows = report.agentSummary
		.map(
			(a) => `
      <tr class="${agentClass(a.agentType)}">
        <td>${escapeHtml(a.agentType)}</td>
        <td>${a.tasksAssigned}</td>
        <td>${a.tasksCompleted}</td>
        <td>${a.tasksFailed}</td>
        <td>${formatDurationHtml(a.avgDurationMs)}</td>
        <td>${formatCostHtml(a.totalCostUsd)}</td>
      </tr>`,
		)
		.join("");

	const improvements = report.routingInsights.filter((r) => r.couldImprove);
	const improvementsHtml =
		improvements.length > 0
			? improvements
					.map((r) => `<li><strong>Task ${escapeHtml(r.taskId)}:</strong> ${escapeHtml(r.improvementHint)}</li>`)
					.join("")
			: "<li>No routing improvements suggested.</li>";

	const issuesHtml =
		report.issues.length > 0
			? report.issues
					.map(
						(i) =>
							`<div class="issue-${i.severity}">
              <strong>${i.severity === "error" ? "✗" : "⚠"}</strong>
              ${i.taskId ? `Task ${escapeHtml(i.taskId)}: ` : "Goal: "}${escapeHtml(i.message)}
            </div>`,
					)
					.join("")
			: "<p>No issues detected.</p>";

	const brandingFooter =
		options.includeBranding !== false
			? `<footer>Generated by Amoena Mission Control • ${timestamp}</footer>`
			: "";

	const rawJsonSection =
		options.includeRawJson === true
			? `<h2>Raw JSON</h2><pre>${escapeHtml(JSON.stringify(report, null, 2))}</pre>`
			: "";

	return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; max-width: 900px; margin: 0 auto; padding: 24px; background: #0f0f0f; color: #e0e0e0; }
    h1 { color: #fff; border-bottom: 2px solid #333; padding-bottom: 12px; }
    h2 { color: #ccc; margin-top: 32px; }
    .status-completed { color: #4caf50; }
    .status-failed { color: #f44336; }
    .status-partial { color: #ff9800; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th, td { padding: 8px 12px; border: 1px solid #333; text-align: left; }
    th { background: #1a1a1a; }
    .metric-card { display: inline-block; background: #1a1a1a; border-radius: 8px; padding: 16px; margin: 8px; min-width: 150px; }
    .metric-value { font-size: 24px; font-weight: bold; }
    .metric-label { color: #999; font-size: 14px; }
    .agent-claude { border-left: 3px solid #FF6B35; }
    .agent-codex { border-left: 3px solid #00C853; }
    .agent-gemini { border-left: 3px solid #2196F3; }
    .issue-warning { background: #332b00; padding: 8px; border-radius: 4px; margin: 4px 0; }
    .issue-error { background: #330000; padding: 8px; border-radius: 4px; margin: 4px 0; }
    .redacted { background: #440000; color: #ff6666; padding: 2px 6px; border-radius: 3px; font-family: monospace; }
    footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #333; color: #666; font-size: 12px; }
    pre { background: #1a1a1a; padding: 16px; border-radius: 6px; overflow-x: auto; font-size: 13px; }
    ul { padding-left: 20px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <p>
    <strong>Status:</strong> <span class="${statusClass(report.runStatus)}">${report.runStatus}</span> &nbsp;
    <strong>Duration:</strong> ${formatDurationHtml(report.totalDurationMs)} &nbsp;
    <strong>Total Cost:</strong> ${formatCostHtml(report.costSummary.totalUsd)}
  </p>

  <h2>Summary</h2>
  <div>
    <div class="metric-card"><div class="metric-value">${tasks.length}</div><div class="metric-label">Total Tasks</div></div>
    <div class="metric-card"><div class="metric-value status-completed">${completed}</div><div class="metric-label">Completed</div></div>
    <div class="metric-card"><div class="metric-value status-failed">${failed}</div><div class="metric-label">Failed</div></div>
  </div>

  <h2>Agent Performance</h2>
  ${
		report.agentSummary.length > 0
			? `<table>
    <thead><tr><th>Agent</th><th>Tasks</th><th>Completed</th><th>Failed</th><th>Avg Duration</th><th>Cost</th></tr></thead>
    <tbody>${agentRows}</tbody>
  </table>`
			: "<p>No agent data available.</p>"
	}

  <h2>Task Breakdown</h2>
  ${
		tasks.length > 0
			? `<table>
    <thead><tr><th>Description</th><th>Type</th><th>Status</th><th>Agent</th><th>Duration</th><th>Cost</th><th>Error</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>`
			: "<p>No tasks recorded.</p>"
	}

  <h2>Routing Insights</h2>
  <ul>${improvementsHtml}</ul>

  <h2>Issues</h2>
  ${issuesHtml}

  ${rawJsonSection}
  ${brandingFooter}
</body>
</html>`;
}

function exportMarkdown(report: RunReport, options: ExportOptions): string {
	return renderMarkdown(report);
}

function exportJson(report: RunReport, _options: ExportOptions): string {
	return JSON.stringify(report, null, 2);
}

/** Export a run report in the specified format */
export function exportReport(report: RunReport, options: ExportOptions): ExportResult {
	const shouldScrub = options.scrubSecrets !== false;
	let workingReport = report;
	let secretsRedacted = 0;

	if (shouldScrub) {
		const { report: scrubbed, totalRedacted } = scrubReport(report);
		workingReport = scrubbed;
		secretsRedacted = totalRedacted;
	}

	let content: string;
	let mimeType: string;

	switch (options.format) {
		case "html":
			content = exportHtml(workingReport, options);
			mimeType = "text/html";
			break;
		case "markdown":
			content = exportMarkdown(workingReport, options);
			mimeType = "text/markdown";
			break;
		case "json":
			content = exportJson(workingReport, options);
			mimeType = "application/json";
			break;
		default:
			throw new Error(`Unknown export format: ${options.format}`);
	}

	return {
		content,
		mimeType,
		filename: generateFilename(report, options.format),
		secretsRedacted,
	};
}

/** Trigger a browser file download */
export function downloadFile(content: string, filename: string, mimeType: string): void {
	const blob = new Blob([content], { type: mimeType });
	const url = URL.createObjectURL(blob);
	const anchor = document.createElement("a");
	anchor.href = url;
	anchor.download = filename;
	document.body.appendChild(anchor);
	anchor.click();
	document.body.removeChild(anchor);
	URL.revokeObjectURL(url);
}
