import type { MemoryEntry } from "./types";

export const initialMemoryEntries: MemoryEntry[] = [
  {
    key: "auth.strategy",
    source: "auto",
    scope: "workspace",
    type: "architecture",
    pinned: true,
    value: "JWT with refresh token rotation. Access tokens expire in 15 minutes, refresh tokens in 7 days with rotation.",
    timestamp: "2 min ago",
    size: "142B",
    session: "JWT Auth Refactor",
    agent: "Claude 4 Sonnet",
  },
  {
    key: "api.versioning",
    source: "manual",
    scope: "global",
    type: "architecture",
    pinned: false,
    value: "URL path prefix /v1/ for all API endpoints. Header-based versioning rejected.",
    timestamp: "1 hour ago",
    size: "89B",
  },
  {
    key: "db.pool_config",
    source: "agent",
    scope: "workspace",
    type: "code_pattern",
    pinned: false,
    value: "Max 25 connections, min 5, idle timeout 30s. Using deadpool-postgres.",
    timestamp: "3 hours ago",
    size: "204B",
    session: "DB Optimization",
    agent: "Claude 4 Sonnet",
  },
  {
    key: "error.handling",
    source: "auto",
    scope: "global",
    type: "code_pattern",
    pinned: true,
    value: "Use thiserror for library errors, anyhow for application errors. All HTTP errors return RFC 7807 Problem Details.",
    timestamp: "Yesterday",
    size: "311B",
  },
  {
    key: "testing.strategy",
    source: "manual",
    scope: "workspace",
    type: "summary",
    pinned: false,
    value: "Integration tests with testcontainers for Postgres. Unit tests for business logic only.",
    timestamp: "2 days ago",
    size: "167B",
    session: "Testing Setup",
  },
];
