import { beforeEach, describe, expect, it, vi } from "vitest";

const { mockPrepare, mockRun, mockGet, mockAll } = vi.hoisted(() => {
	const mockRun = vi.fn(() => ({ lastInsertRowid: 1, changes: 1 }));
	const mockGet = vi.fn((): any => ({ count: 0, sessions: 0, input_tokens: 0, output_tokens: 0, total_cost: 0 }));
	const mockAll = vi.fn(() => []);
	const mockPrepare = vi.fn(() => ({ run: mockRun, get: mockGet, all: mockAll }));
	return { mockPrepare, mockRun, mockGet, mockAll };
});

vi.mock("better-sqlite3", () => ({
	default: vi.fn(() => ({
		prepare: mockPrepare, pragma: vi.fn(), exec: vi.fn(), close: vi.fn(),
		transaction: vi.fn((fn: any) => fn),
	})),
}));
vi.mock("@/lib/config", () => ({ config: { dbPath: ":memory:", dataDir: "/tmp/test" }, ensureDirExists: vi.fn() }));
vi.mock("@/lib/migrations", () => ({ runMigrations: vi.fn() }));
vi.mock("@/lib/password", () => ({ hashPassword: vi.fn() }));
vi.mock("@/lib/logger", () => ({ logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() } }));
vi.mock("@/lib/event-bus", () => ({ eventBus: { broadcast: vi.fn(), on: vi.fn(), emit: vi.fn() } }));
vi.mock("@/lib/auto-credentials", () => ({ ensureAutoGeneratedCredentials: vi.fn() }));
vi.mock("@/lib/mentions", () => ({ parseMentions: vi.fn(() => []) }));
vi.mock("@/lib/webhooks", () => ({ initWebhookListener: vi.fn() }));
vi.mock("@/lib/scheduler", () => ({ initScheduler: vi.fn() }));

describe("agent-optimizer", () => {
	beforeEach(() => { vi.clearAllMocks(); });

	it("analyzeTokenEfficiency returns efficiency data", async () => {
		mockGet.mockReturnValue({ sessions: 5, input_tokens: 100, output_tokens: 200, total_cost: 0.5 });
		const { analyzeTokenEfficiency } = await import("@/lib/agent-optimizer");
		const result = analyzeTokenEfficiency("test-agent");
		expect(result).toBeDefined();
		expect(result.agentName).toBe("test-agent");
		expect(typeof result.totalTokens).toBe("number");
		expect(typeof result.totalCostUsd).toBe("number");
	});

	it("analyzeToolPatterns returns patterns", async () => {
		mockGet.mockReturnValue({ total: 0, unique_tools: 0, failures: 0, avg_duration: 0 });
		mockAll.mockReturnValue([]);
		const { analyzeToolPatterns } = await import("@/lib/agent-optimizer");
		const result = analyzeToolPatterns("test-agent");
		expect(result).toBeDefined();
	});

	it("getFleetBenchmarks returns benchmarks array", async () => {
		mockAll.mockReturnValue([]);
		const { getFleetBenchmarks } = await import("@/lib/agent-optimizer");
		const result = getFleetBenchmarks();
		expect(Array.isArray(result)).toBe(true);
	});

	it("generateRecommendations returns recommendations array", async () => {
		mockGet.mockReturnValue({ sessions: 0, input_tokens: 0, output_tokens: 0, total_cost: 0, total: 0, unique_tools: 0, failures: 0, avg_duration: 0 });
		mockAll.mockReturnValue([]);
		const { generateRecommendations } = await import("@/lib/agent-optimizer");
		const result = generateRecommendations("test-agent");
		expect(Array.isArray(result)).toBe(true);
	});
});
