import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/config", () => ({
	config: { dataDir: "/tmp/test-auto-creds" },
	ensureDirExists: vi.fn(),
}));

vi.mock("@/lib/logger", () => ({
	logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}));

vi.mock("node:fs", async () => {
	const actual = await vi.importActual<typeof import("node:fs")>("node:fs");
	return {
		...actual,
		existsSync: vi.fn(() => false),
		readFileSync: vi.fn(() => ""),
		writeFileSync: vi.fn(),
	};
});

describe("auto-credentials", () => {
	const originalEnv = { ...process.env };

	beforeEach(() => {
		vi.clearAllMocks();
		vi.resetModules();
		delete process.env.AUTH_SECRET;
		delete process.env.API_KEY;
		process.env.NEXT_PHASE = "";
	});

	afterEach(() => {
		process.env = { ...originalEnv };
	});

	it("skips during build phase", async () => {
		process.env.NEXT_PHASE = "phase-production-build";
		const { ensureAutoGeneratedCredentials } = await import("@/lib/auto-credentials");
		ensureAutoGeneratedCredentials();
		// Should not have set AUTH_SECRET
	});

	it("auto-generates AUTH_SECRET when not set", async () => {
		delete process.env.AUTH_SECRET;
		delete process.env.API_KEY;
		const { ensureAutoGeneratedCredentials } = await import("@/lib/auto-credentials");
		ensureAutoGeneratedCredentials();
		expect(process.env.AUTH_SECRET).toBeTruthy();
		expect(process.env.AUTH_SECRET!.length).toBeGreaterThan(10);
	});

	it("auto-generates API_KEY when not set", async () => {
		delete process.env.API_KEY;
		delete process.env.AUTH_SECRET;
		const { ensureAutoGeneratedCredentials } = await import("@/lib/auto-credentials");
		ensureAutoGeneratedCredentials();
		expect(process.env.API_KEY).toBeTruthy();
		expect(process.env.API_KEY!.length).toBeGreaterThan(10);
	});

	it("preserves existing AUTH_SECRET", async () => {
		process.env.AUTH_SECRET = "my-real-secret";
		process.env.API_KEY = "my-real-key";
		const { ensureAutoGeneratedCredentials } = await import("@/lib/auto-credentials");
		ensureAutoGeneratedCredentials();
		expect(process.env.AUTH_SECRET).toBe("my-real-secret");
	});

	it("replaces placeholder AUTH_SECRET", async () => {
		process.env.AUTH_SECRET = "random-secret-for-legacy-cookies";
		delete process.env.API_KEY;
		const { ensureAutoGeneratedCredentials } = await import("@/lib/auto-credentials");
		ensureAutoGeneratedCredentials();
		expect(process.env.AUTH_SECRET).not.toBe("random-secret-for-legacy-cookies");
	});
});
