import { beforeEach, describe, expect, it, vi } from "vitest";

const { mockPrepare, mockPragma, mockExec, mockClose, mockBackup, mockRun, mockGet, mockAll, mockBroadcast } = vi.hoisted(() => {
	const mockRun = vi.fn(() => ({ lastInsertRowid: 1, changes: 1 }));
	const mockGet = vi.fn((): any => ({ count: 0 }));
	const mockAll = vi.fn(() => []);
	const mockPrepare = vi.fn(() => ({ run: mockRun, get: mockGet, all: mockAll }));
	const mockPragma = vi.fn();
	const mockExec = vi.fn();
	const mockClose = vi.fn();
	const mockBackup = vi.fn();
	const mockBroadcast = vi.fn();
	return { mockPrepare, mockPragma, mockExec, mockClose, mockBackup, mockRun, mockGet, mockAll, mockBroadcast };
});

vi.mock("better-sqlite3", () => ({
	default: vi.fn(() => ({
		prepare: mockPrepare,
		pragma: mockPragma,
		exec: mockExec,
		close: mockClose,
		backup: mockBackup,
		transaction: vi.fn((fn: any) => fn),
	})),
}));

vi.mock("@/lib/config", () => ({
	config: { dbPath: ":memory:", dataDir: "/tmp/test-data" },
	ensureDirExists: vi.fn(),
}));

vi.mock("@/lib/migrations", () => ({ runMigrations: vi.fn() }));
vi.mock("@/lib/password", () => ({
	hashPassword: vi.fn((p: string) => `hashed:${p}`),
}));
vi.mock("@/lib/logger", () => ({
	logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}));
vi.mock("@/lib/event-bus", () => ({
	eventBus: { broadcast: mockBroadcast, on: vi.fn(), emit: vi.fn() },
}));
vi.mock("@/lib/auto-credentials", () => ({
	ensureAutoGeneratedCredentials: vi.fn(),
}));
vi.mock("@/lib/mentions", () => ({
	parseMentions: vi.fn((text: string) => {
		const matches = text.match(/@(\w+)/g);
		return matches ? matches.map((m) => m.slice(1)) : [];
	}),
}));
vi.mock("@/lib/webhooks", () => ({
	initWebhookListener: vi.fn(),
}));
vi.mock("@/lib/scheduler", () => ({
	initScheduler: vi.fn(),
}));

describe("db module", () => {
	beforeEach(() => {
		vi.resetModules();
		vi.clearAllMocks();
		process.env.NEXT_PHASE = "";
		process.env.AMOENA_TEST_MODE = "1";
	});

	it("resolveSeedAuthPassword returns null when no env vars set", async () => {
		const { resolveSeedAuthPassword } = await import("@/lib/db");
		const result = resolveSeedAuthPassword({});
		expect(result).toBeNull();
	});

	it("resolveSeedAuthPassword returns AUTH_PASS when set", async () => {
		const { resolveSeedAuthPassword } = await import("@/lib/db");
		const result = resolveSeedAuthPassword({ AUTH_PASS: "my-password" });
		expect(result).toBe("my-password");
	});

	it("resolveSeedAuthPassword decodes valid AUTH_PASS_B64", async () => {
		const { resolveSeedAuthPassword } = await import("@/lib/db");
		const encoded = Buffer.from("secret123", "utf8").toString("base64");
		const result = resolveSeedAuthPassword({ AUTH_PASS_B64: encoded });
		expect(result).toBe("secret123");
	});

	it("resolveSeedAuthPassword falls back to AUTH_PASS on invalid base64", async () => {
		const { resolveSeedAuthPassword } = await import("@/lib/db");
		const result = resolveSeedAuthPassword({
			AUTH_PASS_B64: "!!!not-base64!!!",
			AUTH_PASS: "fallback",
		});
		expect(result).toBe("fallback");
	});

	it("resolveSeedAuthPassword falls back when b64 is empty after decode", async () => {
		const { resolveSeedAuthPassword } = await import("@/lib/db");
		// Empty base64 decodes to empty string
		const result = resolveSeedAuthPassword({
			AUTH_PASS_B64: "",
			AUTH_PASS: "fallback",
		});
		expect(result).toBe("fallback");
	});

	it("getDatabase returns a database instance", async () => {
		const { getDatabase } = await import("@/lib/db");
		const db = getDatabase();
		expect(db).toBeDefined();
		expect(mockPragma).toHaveBeenCalled();
	});

	it("closeDatabase closes the connection", async () => {
		const { getDatabase, closeDatabase } = await import("@/lib/db");
		getDatabase();
		closeDatabase();
		expect(mockClose).toHaveBeenCalled();
	});

	it("closeDatabase is no-op when no db open", async () => {
		const { closeDatabase } = await import("@/lib/db");
		closeDatabase();
		// Should not throw
	});

	it("needsFirstTimeSetup returns true when no users", async () => {
		mockGet.mockReturnValueOnce({ count: 0 });
		const { needsFirstTimeSetup, getDatabase } = await import("@/lib/db");
		getDatabase(); // initialize
		const result = needsFirstTimeSetup();
		expect(result).toBe(true);
	});

	it("needsFirstTimeSetup returns false when users exist", async () => {
		const { needsFirstTimeSetup, getDatabase } = await import("@/lib/db");
		getDatabase();
		mockGet.mockReturnValueOnce({ count: 3 });
		const result = needsFirstTimeSetup();
		expect(result).toBe(false);
	});

	it("db_helpers.parseMentions extracts @mentions", async () => {
		const { db_helpers } = await import("@/lib/db");
		const result = db_helpers.parseMentions("hello @alice and @bob");
		expect(result).toEqual(["alice", "bob"]);
	});

	it("db_helpers.logActivity inserts and broadcasts", async () => {
		const { db_helpers, getDatabase } = await import("@/lib/db");
		getDatabase();
		db_helpers.logActivity("test", "task", 1, "admin", "test action");
		expect(mockRun).toHaveBeenCalled();
		expect(mockBroadcast).toHaveBeenCalledWith(
			"activity.created",
			expect.objectContaining({ type: "test", entity_type: "task" }),
		);
	});

	it("db_helpers.createNotification inserts and broadcasts", async () => {
		const { db_helpers, getDatabase } = await import("@/lib/db");
		getDatabase();
		db_helpers.createNotification("admin", "info", "Test", "Hello");
		expect(mockRun).toHaveBeenCalled();
		expect(mockBroadcast).toHaveBeenCalledWith(
			"notification.created",
			expect.objectContaining({ recipient: "admin", type: "info" }),
		);
	});

	it("logAuditEvent inserts audit log and broadcasts security events", async () => {
		const { logAuditEvent, getDatabase } = await import("@/lib/db");
		getDatabase();
		logAuditEvent({ action: "login_failed", actor: "user1" });
		expect(mockRun).toHaveBeenCalled();
		expect(mockBroadcast).toHaveBeenCalledWith(
			"audit.security",
			expect.objectContaining({ action: "login_failed" }),
		);
	});

	it("logAuditEvent does not broadcast non-security events", async () => {
		const { logAuditEvent, getDatabase } = await import("@/lib/db");
		getDatabase();
		mockBroadcast.mockClear();
		logAuditEvent({ action: "settings_changed", actor: "admin" });
		expect(mockRun).toHaveBeenCalled();
		// Should only be called for the insert, not broadcast
		expect(mockBroadcast).not.toHaveBeenCalledWith(
			"audit.security",
			expect.anything(),
		);
	});

	it("appendProvisionEvent inserts event", async () => {
		const { appendProvisionEvent, getDatabase } = await import("@/lib/db");
		getDatabase();
		appendProvisionEvent({ job_id: 1, message: "test event" });
		expect(mockRun).toHaveBeenCalled();
	});

	it("db_helpers.ensureTaskSubscription is no-op for empty agent", async () => {
		const { db_helpers, getDatabase } = await import("@/lib/db");
		getDatabase();
		mockRun.mockClear();
		db_helpers.ensureTaskSubscription(1, "");
		expect(mockRun).not.toHaveBeenCalled();
	});

	it("db_helpers.getRecentActivities returns array", async () => {
		const { db_helpers, getDatabase } = await import("@/lib/db");
		getDatabase();
		mockAll.mockReturnValueOnce([{ id: 1, type: "test" }]);
		const result = db_helpers.getRecentActivities(10);
		expect(result).toEqual([{ id: 1, type: "test" }]);
	});

	it("db_helpers.getUnreadNotifications returns array", async () => {
		const { db_helpers, getDatabase } = await import("@/lib/db");
		getDatabase();
		mockAll.mockReturnValueOnce([]);
		const result = db_helpers.getUnreadNotifications("admin");
		expect(result).toEqual([]);
	});
});
