import { beforeEach, describe, expect, it, vi } from "vitest";

const { mockPrepare, mockRun, mockGet, mockAll } = vi.hoisted(() => {
	const mockRun = vi.fn(() => ({ lastInsertRowid: 1, changes: 1 }));
	const mockGet = vi.fn((): any => ({ count: 0 }));
	const mockAll = vi.fn(() => []);
	const mockPrepare = vi.fn(() => ({ run: mockRun, get: mockGet, all: mockAll }));
	return { mockPrepare, mockRun, mockGet, mockAll };
});

vi.mock("better-sqlite3", () => ({
	default: vi.fn(() => ({
		prepare: mockPrepare,
		pragma: vi.fn(),
		exec: vi.fn(),
		close: vi.fn(),
		transaction: vi.fn((fn: any) => fn),
	})),
}));

vi.mock("@/lib/config", () => ({
	config: { dbPath: ":memory:", dataDir: "/tmp/test-data" },
	ensureDirExists: vi.fn(),
}));
vi.mock("@/lib/migrations", () => ({ runMigrations: vi.fn() }));
vi.mock("@/lib/password", () => ({ hashPassword: vi.fn((p: string) => `hashed:${p}`) }));
vi.mock("@/lib/logger", () => ({
	logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}));
vi.mock("@/lib/event-bus", () => ({
	eventBus: { broadcast: vi.fn(), on: vi.fn(), emit: vi.fn() },
}));
vi.mock("@/lib/auto-credentials", () => ({ ensureAutoGeneratedCredentials: vi.fn() }));
vi.mock("@/lib/mentions", () => ({ parseMentions: vi.fn(() => []) }));
vi.mock("@/lib/webhooks", () => ({ initWebhookListener: vi.fn() }));
vi.mock("@/lib/scheduler", () => ({ initScheduler: vi.fn() }));

vi.mock("@/lib/github", () => ({
	ensureLabels: vi.fn().mockResolvedValue(undefined),
	fetchIssue: vi.fn().mockResolvedValue({ number: 1, title: "test", labels: [] }),
	fetchIssues: vi.fn().mockResolvedValue([]),
	createIssue: vi.fn().mockResolvedValue({ number: 1 }),
	updateIssue: vi.fn().mockResolvedValue(undefined),
}));

vi.mock("@/lib/github-label-map", () => ({
	ALL_MC_LABELS: [],
	ALL_PRIORITY_LABEL_NAMES: [],
	ALL_STATUS_LABEL_NAMES: [],
	labelToPriority: vi.fn(() => "medium"),
	labelToStatus: vi.fn(() => "inbox"),
	priorityToLabel: vi.fn(() => "priority:medium"),
	statusToLabel: vi.fn(() => "status:inbox"),
}));

describe("github-sync-engine", () => {
	beforeEach(() => {
		vi.clearAllMocks();
	});

	it("initializeLabels calls ensureLabels", async () => {
		const { initializeLabels } = await import("@/lib/github-sync-engine");
		const { ensureLabels } = await import("@/lib/github");
		await initializeLabels("owner/repo");
		expect(ensureLabels).toHaveBeenCalledWith("owner/repo", expect.any(Array));
	});

	it("pushTaskToGitHub is a no-op without repo", async () => {
		const { pushTaskToGitHub } = await import("@/lib/github-sync-engine");
		const { createIssue } = await import("@/lib/github");
		await pushTaskToGitHub(
			{ id: 1, title: "Test", status: "inbox", priority: "medium" },
			{ id: 1 },
		);
		expect(createIssue).not.toHaveBeenCalled();
	});
});
