import { beforeEach, describe, expect, it, vi } from "vitest";

const { mockPrepare, mockRun, mockGet, mockAll } = vi.hoisted(() => {
	const mockRun = vi.fn(() => ({ lastInsertRowid: 1, changes: 1 }));
	const mockGet = vi.fn((): any => ({ count: 0 }));
	const mockAll = vi.fn(() => []);
	const mockPrepare = vi.fn(() => ({ run: mockRun, get: mockGet, all: mockAll }));
	return { mockPrepare, mockRun, mockGet, mockAll };
});

vi.mock("better-sqlite3", () => ({
	default: vi.fn(() => ({
		prepare: mockPrepare, pragma: vi.fn(), exec: vi.fn(), close: vi.fn(),
		transaction: vi.fn((fn: any) => fn),
	})),
}));
vi.mock("@/lib/config", () => ({ config: { dbPath: ":memory:", dataDir: "/tmp/test" }, ensureDirExists: vi.fn() }));
vi.mock("@/lib/migrations", () => ({ runMigrations: vi.fn() }));
vi.mock("@/lib/password", () => ({ hashPassword: vi.fn() }));
vi.mock("@/lib/logger", () => ({ logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() } }));
vi.mock("@/lib/event-bus", () => ({ eventBus: { broadcast: vi.fn(), on: vi.fn(), emit: vi.fn() } }));
vi.mock("@/lib/auto-credentials", () => ({ ensureAutoGeneratedCredentials: vi.fn() }));
vi.mock("@/lib/mentions", () => ({ parseMentions: vi.fn(() => []) }));
vi.mock("@/lib/webhooks", () => ({ initWebhookListener: vi.fn() }));
vi.mock("@/lib/scheduler", () => ({ initScheduler: vi.fn() }));

describe("mcp-audit", () => {
	beforeEach(() => { vi.clearAllMocks(); });

	it("logMcpCall inserts a record and returns id", async () => {
		const { logMcpCall } = await import("@/lib/mcp-audit");
		const id = logMcpCall({
			serverName: "test-server",
			toolName: "test-tool",
			args: { key: "value" },
			callerAgent: "agent-1",
		});
		expect(typeof id).toBe("number");
		expect(mockRun).toHaveBeenCalled();
	});

	it("getMcpCallStats returns stats", async () => {
		mockAll.mockReturnValue([]);
		mockGet.mockReturnValue({ total: 0 });
		const { getMcpCallStats } = await import("@/lib/mcp-audit");
		const stats = getMcpCallStats();
		expect(stats).toBeDefined();
	});
});
