import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const { mockPrepare, mockRun, mockGet, mockAll } = vi.hoisted(() => {
	const mockRun = vi.fn(() => ({ lastInsertRowid: 1, changes: 1 }));
	const mockGet = vi.fn((): any => undefined);
	const mockAll = vi.fn(() => []);
	const mockPrepare = vi.fn(() => ({ run: mockRun, get: mockGet, all: mockAll }));
	return { mockPrepare, mockRun, mockGet, mockAll };
});

vi.mock("better-sqlite3", () => ({
	default: vi.fn(() => ({
		prepare: mockPrepare,
		pragma: vi.fn(),
		exec: vi.fn(),
		close: vi.fn(),
		backup: vi.fn().mockResolvedValue(undefined),
		transaction: vi.fn((fn: any) => fn),
	})),
}));

vi.mock("@/lib/config", () => ({
	config: {
		dbPath: ":memory:",
		dataDir: "/tmp/test-data",
		amoenaStateDir: "/tmp/amoena",
		retention: { activities: 30, auditLog: 90, notifications: 14, pipelineRuns: 30, tokenUsage: 30, gatewaySessions: 7 },
		tokensPath: "/tmp/tokens.json",
	},
	ensureDirExists: vi.fn(),
}));

vi.mock("@/lib/migrations", () => ({ runMigrations: vi.fn() }));
vi.mock("@/lib/password", () => ({ hashPassword: vi.fn((p: string) => `hashed:${p}`) }));
vi.mock("@/lib/logger", () => ({
	logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}));
vi.mock("@/lib/event-bus", () => ({
	eventBus: { broadcast: vi.fn(), on: vi.fn(), emit: vi.fn() },
}));
vi.mock("@/lib/auto-credentials", () => ({ ensureAutoGeneratedCredentials: vi.fn() }));
vi.mock("@/lib/mentions", () => ({ parseMentions: vi.fn(() => []) }));
vi.mock("@/lib/webhooks", () => ({
	initWebhookListener: vi.fn(),
	processWebhookRetries: vi.fn().mockResolvedValue({ ok: true, message: "done" }),
}));
vi.mock("@/lib/agent-sync", () => ({
	syncAgentsFromConfig: vi.fn().mockResolvedValue({ created: 0, updated: 0, synced: 0 }),
}));
vi.mock("@/lib/claude-sessions", () => ({
	syncClaudeSessions: vi.fn().mockResolvedValue({ ok: true, message: "scanned" }),
}));
vi.mock("@/lib/local-agent-sync", () => ({
	syncLocalAgents: vi.fn().mockResolvedValue({ ok: true, message: "synced" }),
}));
vi.mock("@/lib/skill-sync", () => ({
	syncSkillsFromDisk: vi.fn().mockResolvedValue({ ok: true, message: "synced" }),
}));
vi.mock("@/lib/task-dispatch", () => ({
	autoRouteInboxTasks: vi.fn().mockResolvedValue({ ok: true, message: "routed" }),
	dispatchAssignedTasks: vi.fn().mockResolvedValue({ ok: true, message: "dispatched" }),
	requeueStaleTasks: vi.fn().mockResolvedValue({ ok: true, message: "requeued" }),
	runAegisReviews: vi.fn().mockResolvedValue({ ok: true, message: "reviewed" }),
}));
vi.mock("@/lib/recurring-tasks", () => ({
	spawnRecurringTasks: vi.fn().mockResolvedValue({ ok: true, message: "spawned" }),
}));
vi.mock("@/lib/sessions", () => ({
	getAgentLiveStatuses: vi.fn(() => new Map()),
	pruneGatewaySessionsOlderThan: vi.fn(() => ({ deleted: 0 })),
}));

describe("scheduler", () => {
	beforeEach(() => {
		vi.resetModules();
		vi.clearAllMocks();
		vi.useFakeTimers();
		process.env.AMOENA_TEST_MODE = "1";
		process.env.NEXT_PHASE = "";
	});

	afterEach(() => {
		vi.useRealTimers();
	});

	it("initScheduler registers tasks and starts tick interval", async () => {
		const { initScheduler, getSchedulerStatus, stopScheduler } = await import("@/lib/scheduler");
		initScheduler();
		const status = getSchedulerStatus();
		expect(status.length).toBeGreaterThan(0);
		expect(status.some((t) => t.id === "auto_backup")).toBe(true);
		expect(status.some((t) => t.id === "agent_heartbeat")).toBe(true);
		expect(status.some((t) => t.id === "task_dispatch")).toBe(true);
		stopScheduler();
	});

	it("initScheduler is idempotent", async () => {
		const { initScheduler, stopScheduler } = await import("@/lib/scheduler");
		initScheduler();
		initScheduler(); // second call should be no-op
		stopScheduler();
	});

	it("stopScheduler clears interval", async () => {
		const { initScheduler, stopScheduler, getSchedulerStatus } = await import("@/lib/scheduler");
		initScheduler();
		stopScheduler();
		// After stop, status still shows tasks but interval is cleared
		const status = getSchedulerStatus();
		expect(status.length).toBeGreaterThan(0);
	});

	it("getSchedulerStatus returns empty array before init", async () => {
		const { getSchedulerStatus } = await import("@/lib/scheduler");
		const status = getSchedulerStatus();
		expect(status).toEqual([]);
	});

	it("triggerTask returns result for known tasks", async () => {
		const { triggerTask } = await import("@/lib/scheduler");
		const result = await triggerTask("webhook_retry");
		expect(result.ok).toBe(true);
	});

	it("triggerTask returns error for unknown task", async () => {
		const { triggerTask } = await import("@/lib/scheduler");
		const result = await triggerTask("nonexistent");
		expect(result.ok).toBe(false);
		expect(result.message).toContain("Unknown task");
	});

	it("triggerTask handles task_dispatch", async () => {
		const { triggerTask } = await import("@/lib/scheduler");
		const result = await triggerTask("task_dispatch");
		expect(result.ok).toBe(true);
	});

	it("triggerTask handles aegis_review", async () => {
		const { triggerTask } = await import("@/lib/scheduler");
		const result = await triggerTask("aegis_review");
		expect(result.ok).toBe(true);
	});

	it("triggerTask handles recurring_task_spawn", async () => {
		const { triggerTask } = await import("@/lib/scheduler");
		const result = await triggerTask("recurring_task_spawn");
		expect(result.ok).toBe(true);
	});

	it("triggerTask handles stale_task_requeue", async () => {
		const { triggerTask } = await import("@/lib/scheduler");
		const result = await triggerTask("stale_task_requeue");
		expect(result.ok).toBe(true);
	});

	it("triggerTask handles claude_session_scan", async () => {
		const { triggerTask } = await import("@/lib/scheduler");
		const result = await triggerTask("claude_session_scan");
		expect(result.ok).toBe(true);
	});

	it("triggerTask handles skill_sync", async () => {
		const { triggerTask } = await import("@/lib/scheduler");
		const result = await triggerTask("skill_sync");
		expect(result.ok).toBe(true);
	});

	it("triggerTask handles local_agent_sync", async () => {
		const { triggerTask } = await import("@/lib/scheduler");
		const result = await triggerTask("local_agent_sync");
		expect(result.ok).toBe(true);
	});

	it("triggerTask handles gateway_agent_sync", async () => {
		const { triggerTask } = await import("@/lib/scheduler");
		const result = await triggerTask("gateway_agent_sync");
		expect(result.ok).toBe(true);
		expect(result.message).toContain("Gateway sync");
	});
});
