import { describe, expect, it, vi } from "vitest";

const { mockPrepare, mockRun, mockGet, mockAll } = vi.hoisted(() => {
	const mockRun = vi.fn(() => ({ lastInsertRowid: 1, changes: 1 }));
	const mockGet = vi.fn((): any => ({ count: 0 }));
	const mockAll = vi.fn(() => []);
	const mockPrepare = vi.fn(() => ({ run: mockRun, get: mockGet, all: mockAll }));
	return { mockPrepare, mockRun, mockGet, mockAll };
});

vi.mock("better-sqlite3", () => ({
	default: vi.fn(() => ({
		prepare: mockPrepare,
		pragma: vi.fn(),
		exec: vi.fn(),
		close: vi.fn(),
		transaction: vi.fn((fn: any) => fn),
	})),
}));

vi.mock("@/lib/config", () => ({
	config: {
		dbPath: ":memory:",
		dataDir: "/tmp/test-data",
		envPath: "/tmp/.env",
		amoenaStateDir: "/tmp/amoena",
		amoenaConfigPath: "/tmp/amoena/amoena.json",
		homeDir: "/tmp/home",
	},
	ensureDirExists: vi.fn(),
}));

vi.mock("@/lib/migrations", () => ({ runMigrations: vi.fn() }));
vi.mock("@/lib/password", () => ({ hashPassword: vi.fn((p: string) => `hashed:${p}`) }));
vi.mock("@/lib/logger", () => ({
	logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}));
vi.mock("@/lib/event-bus", () => ({
	eventBus: { broadcast: vi.fn(), on: vi.fn(), emit: vi.fn() },
}));
vi.mock("@/lib/auto-credentials", () => ({ ensureAutoGeneratedCredentials: vi.fn() }));
vi.mock("@/lib/mentions", () => ({ parseMentions: vi.fn(() => []) }));
vi.mock("@/lib/webhooks", () => ({ initWebhookListener: vi.fn() }));
vi.mock("@/lib/scheduler", () => ({ initScheduler: vi.fn() }));

describe("security-scan", () => {
	describe("FIX_SAFETY", () => {
		it("exports a fix safety map", async () => {
			const { FIX_SAFETY } = await import("@/lib/security-scan");
			expect(typeof FIX_SAFETY).toBe("object");
			expect(FIX_SAFETY.env_permissions).toBe("safe");
			expect(FIX_SAFETY.hsts_enabled).toBe("requires-restart");
			expect(FIX_SAFETY.exec_restricted).toBe("requires-review");
		});
	});

	describe("runSecurityScan", () => {
		it("returns a scan result with all categories", async () => {
			const { runSecurityScan } = await import("@/lib/security-scan");
			const result = runSecurityScan();
			expect(result.categories).toBeDefined();
			expect(result.categories.credentials).toBeDefined();
			expect(result.categories.network).toBeDefined();
			expect(result.categories.amoena).toBeDefined();
			expect(result.categories.runtime).toBeDefined();
			expect(result.categories.os).toBeDefined();
			expect(result.score).toBeGreaterThanOrEqual(0);
			expect(result.score).toBeLessThanOrEqual(100);
			expect(["secure", "hardened", "needs-attention", "at-risk"]).toContain(result.overall);
			expect(result.timestamp).toBeGreaterThan(0);
		});

		it("each check has required fields", async () => {
			const { runSecurityScan } = await import("@/lib/security-scan");
			const result = runSecurityScan();
			for (const category of Object.values(result.categories)) {
				for (const check of category.checks) {
					expect(check.id).toBeTruthy();
					expect(check.name).toBeTruthy();
					expect(["pass", "fail", "warn"]).toContain(check.status);
					expect(check.detail).toBeDefined();
					expect(check.fix).toBeDefined();
				}
			}
		});
	});

	describe("readSystemUptimeSeconds", () => {
		it("returns a number or null", async () => {
			const { readSystemUptimeSeconds } = await import("@/lib/security-scan");
			const result = readSystemUptimeSeconds();
			expect(result === null || typeof result === "number").toBe(true);
		});
	});
});
