import { beforeEach, describe, expect, it, vi } from "vitest";

const { mockPrepare, mockRun, mockGet, mockAll } = vi.hoisted(() => {
	const mockRun = vi.fn(() => ({ lastInsertRowid: 42, changes: 1 }));
	const mockGet = vi.fn((): any => ({ count: 0 }));
	const mockAll = vi.fn(() => []);
	const mockPrepare = vi.fn(() => ({ run: mockRun, get: mockGet, all: mockAll }));
	return { mockPrepare, mockRun, mockGet, mockAll };
});

vi.mock("better-sqlite3", () => ({
	default: vi.fn(() => ({
		prepare: mockPrepare, pragma: vi.fn(), exec: vi.fn(), close: vi.fn(),
		transaction: vi.fn((fn: any) => fn),
	})),
}));
vi.mock("@/lib/config", () => ({ config: { dbPath: ":memory:", dataDir: "/tmp/test" }, ensureDirExists: vi.fn() }));
vi.mock("@/lib/migrations", () => ({ runMigrations: vi.fn() }));
vi.mock("@/lib/password", () => ({ hashPassword: vi.fn() }));
vi.mock("@/lib/logger", () => ({ logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() } }));
vi.mock("@/lib/event-bus", () => ({ eventBus: { broadcast: vi.fn(), on: vi.fn(), emit: vi.fn() } }));
vi.mock("@/lib/auto-credentials", () => ({ ensureAutoGeneratedCredentials: vi.fn() }));
vi.mock("@/lib/mentions", () => ({ parseMentions: vi.fn(() => []) }));
vi.mock("@/lib/webhooks", () => ({ initWebhookListener: vi.fn() }));
vi.mock("@/lib/scheduler", () => ({ initScheduler: vi.fn() }));

describe("spawn-history", () => {
	beforeEach(() => { vi.clearAllMocks(); });

	it("recordSpawnStart returns an ID", async () => {
		const { recordSpawnStart } = await import("@/lib/spawn-history");
		const id = recordSpawnStart({ agentName: "test", prompt: "hello", sessionId: "s1" });
		expect(typeof id).toBe("number");
	});

	it("recordSpawnFinish does not throw", async () => {
		const { recordSpawnFinish } = await import("@/lib/spawn-history");
		expect(() => recordSpawnFinish(42, "success", "output text")).not.toThrow();
	});

	it("getSpawnHistory returns array", async () => {
		mockAll.mockReturnValue([]);
		const { getSpawnHistory } = await import("@/lib/spawn-history");
		const result = getSpawnHistory();
		expect(Array.isArray(result)).toBe(true);
	});

	it("getSpawnStats returns stats object", async () => {
		mockGet.mockReturnValue({ total: 0, success: 0, failed: 0 });
		const { getSpawnStats } = await import("@/lib/spawn-history");
		const result = getSpawnStats();
		expect(result).toBeDefined();
	});
});
