import { MarketplaceCategory, MarketplaceItem } from "./types";

export const marketplaceCategories: MarketplaceCategory[] = ["All", "Extensions", "Agent Templates", "Tool Packs", "Memory Packs", "Themes"];

export const allItems: MarketplaceItem[] = [
  { id: "git-pro", name: "Git Integration Pro", author: "amoena-team", installs: "12.4k", installCount: 12400, desc: "Advanced git workflow tools with branch management, stash operations, and interactive rebase support.", category: "Extensions", installed: true, featured: true, trusted: true, version: "2.1.0", permissions: ["file_read", "file_write", "git", "terminal"], signed: true, compatibility: ">=1.0.0", lastUpdated: "2 days ago", rating: 4.8, tags: ["git", "workflow", "vcs"] },
  { id: "code-review", name: "Code Review Agent", author: "community", installs: "8.2k", installCount: 8200, desc: "Automated code review sub-agent that identifies bugs, style issues, and security vulnerabilities.", category: "Agent Templates", installed: false, featured: true, trusted: true, version: "1.3.1", permissions: ["file_read", "git_diff"], signed: true, compatibility: ">=1.0.0", lastUpdated: "1 week ago", rating: 4.6, tags: ["review", "quality", "bugs"] },
  { id: "docker-tools", name: "Docker Tools", author: "amoena-team", installs: "6.1k", installCount: 6100, desc: "Container management toolkit with Dockerfile generation and compose orchestration.", category: "Tool Packs", installed: false, trusted: true, version: "0.9.1", permissions: ["terminal", "file_read", "file_write"], signed: true, compatibility: ">=1.0.0", lastUpdated: "3 days ago", rating: 4.3, tags: ["docker", "containers", "devops"] },
  { id: "rust-patterns", name: "Rust Patterns", author: "community", installs: "4.8k", installCount: 4800, desc: "Idiomatic Rust patterns memory pack with ownership, lifetime, and trait implementation guides.", category: "Memory Packs", installed: true, trusted: true, version: "1.4.2", permissions: ["memory_read", "memory_write"], signed: true, compatibility: ">=1.0.0", lastUpdated: "5 days ago", rating: 4.9, tags: ["rust", "patterns", "language"] },
  { id: "midnight-amethyst", name: "Midnight Amethyst", author: "community", installs: "3.2k", installCount: 3200, desc: "Deep purple color theme with carefully crafted contrast ratios and semantic token support.", category: "Themes", installed: false, trusted: false, version: "1.0.3", permissions: ["theme"], signed: false, compatibility: ">=1.0.0", lastUpdated: "2 weeks ago", rating: 4.1, tags: ["theme", "dark", "purple"] },
  { id: "api-tester", name: "API Tester", author: "amoena-team", installs: "9.7k", installCount: 9700, desc: "REST/GraphQL testing toolkit with request builder, response validation, and collection management.", category: "Tool Packs", installed: false, featured: true, trusted: true, version: "2.0.0", permissions: ["network", "file_read"], signed: true, compatibility: ">=1.0.0", lastUpdated: "1 day ago", rating: 4.7, tags: ["api", "rest", "graphql", "testing"] },
  { id: "security-auditor", name: "Security Auditor", author: "community", installs: "5.5k", installCount: 5500, desc: "Security-focused review agent that scans for common vulnerabilities and misconfigurations.", category: "Agent Templates", installed: false, trusted: true, version: "1.1.0", permissions: ["file_read", "terminal"], signed: true, compatibility: ">=1.0.0", lastUpdated: "4 days ago", rating: 4.4, tags: ["security", "audit", "vulnerabilities"] },
  { id: "ts-expertise", name: "TypeScript Expertise", author: "community", installs: "7.1k", installCount: 7100, desc: "Advanced TypeScript patterns including generics, conditional types, and utility types.", category: "Memory Packs", installed: false, trusted: true, version: "2.0.1", permissions: ["memory_read", "memory_write"], signed: true, compatibility: ">=1.0.0", lastUpdated: "1 week ago", rating: 4.5, tags: ["typescript", "types", "language"] },
  { id: "db-explorer", name: "Database Explorer", author: "amoena-team", installs: "11.2k", installCount: 11200, desc: "Visual database browser with schema inspection, query builder, and migration generator for Postgres, MySQL, and SQLite.", category: "Extensions", installed: false, featured: true, trusted: true, version: "3.0.2", permissions: ["network", "file_read", "file_write", "terminal"], signed: true, compatibility: ">=1.0.0", lastUpdated: "12 hours ago", rating: 4.9, tags: ["database", "sql", "postgres", "mysql"] },
  { id: "test-runner", name: "Test Runner Pro", author: "amoena-team", installs: "8.9k", installCount: 8900, desc: "Integrated test execution with coverage visualization, watch mode, and failure analysis.", category: "Extensions", installed: false, trusted: true, version: "1.5.0", permissions: ["terminal", "file_read"], signed: true, compatibility: ">=1.0.0", lastUpdated: "6 days ago", rating: 4.6, tags: ["testing", "coverage", "ci"] },
  { id: "refactor-agent", name: "Refactoring Agent", author: "community", installs: "3.8k", installCount: 3800, desc: "Automated refactoring agent that identifies code smells, suggests improvements, and applies safe transformations.", category: "Agent Templates", installed: false, trusted: true, version: "0.8.0", permissions: ["file_read", "file_write", "git"], signed: true, compatibility: ">=1.0.0", lastUpdated: "1 week ago", rating: 4.2, tags: ["refactoring", "cleanup", "quality"] },
  { id: "k8s-tools", name: "Kubernetes Toolkit", author: "community", installs: "4.1k", installCount: 4100, desc: "Kubernetes cluster management with deployment templates, helm chart generation, and kubectl shortcuts.", category: "Tool Packs", installed: false, trusted: true, version: "1.2.0", permissions: ["terminal", "file_read", "file_write", "network"], signed: true, compatibility: ">=1.0.0", lastUpdated: "3 days ago", rating: 4.3, tags: ["kubernetes", "k8s", "devops", "containers"] },
  { id: "python-patterns", name: "Python Best Practices", author: "community", installs: "6.3k", installCount: 6300, desc: "Python idioms, async patterns, type hints, and project structure guidelines for modern Python development.", category: "Memory Packs", installed: false, trusted: true, version: "1.7.0", permissions: ["memory_read", "memory_write"], signed: true, compatibility: ">=1.0.0", lastUpdated: "4 days ago", rating: 4.7, tags: ["python", "patterns", "language"] },
  { id: "aurora-theme", name: "Aurora Borealis", author: "community", installs: "2.1k", installCount: 2100, desc: "Northern lights inspired theme with cyan-green gradients and high contrast readability.", category: "Themes", installed: false, trusted: true, version: "1.1.0", permissions: ["theme"], signed: true, compatibility: ">=1.0.0", lastUpdated: "1 week ago", rating: 4.4, tags: ["theme", "dark", "cyan", "green"] },
  { id: "perf-profiler", name: "Performance Profiler", author: "amoena-team", installs: "5.0k", installCount: 5000, desc: "Runtime performance analysis with flame graphs, memory snapshots, and bottleneck detection.", category: "Tool Packs", installed: false, trusted: true, version: "1.0.0", permissions: ["terminal", "file_read", "network"], signed: true, compatibility: ">=1.0.0", lastUpdated: "5 days ago", rating: 4.5, tags: ["performance", "profiling", "optimization"] },
  { id: "doc-writer", name: "Documentation Writer", author: "community", installs: "4.5k", installCount: 4500, desc: "Auto-generates documentation from code, including API references, usage examples, and architecture diagrams.", category: "Agent Templates", installed: false, trusted: false, version: "0.6.2", permissions: ["file_read", "file_write"], signed: false, compatibility: ">=1.0.0", lastUpdated: "2 weeks ago", rating: 3.9, tags: ["documentation", "docs", "markdown"] },
  { id: "solarized-theme", name: "Solarized Precision", author: "community", installs: "1.8k", installCount: 1800, desc: "Classic solarized color scheme adapted for Amoena with both light and dark variants.", category: "Themes", installed: false, trusted: true, version: "2.0.0", permissions: ["theme"], signed: true, compatibility: ">=1.0.0", lastUpdated: "3 weeks ago", rating: 4.0, tags: ["theme", "solarized", "classic"] },
  { id: "go-patterns", name: "Go Idioms Pack", author: "community", installs: "3.4k", installCount: 3400, desc: "Go concurrency patterns, error handling conventions, and project layout best practices.", category: "Memory Packs", installed: false, trusted: true, version: "1.2.1", permissions: ["memory_read", "memory_write"], signed: true, compatibility: ">=1.0.0", lastUpdated: "6 days ago", rating: 4.3, tags: ["go", "golang", "patterns", "language"] },
];
