import type { ManagedAgent } from './types';

export const initialManagedAgents: ManagedAgent[] = [
  {
    name: 'Claude 4 Sonnet',
    type: 'Main',
    source: 'built-in',
    provider: 'Anthropic',
    model: 'claude-4-sonnet',
    status: 'active',
    lastActive: 'Just now',
    role: 'Primary Engineer',
    tools: ['file_edit', 'terminal', 'git', 'browser'],
    permission: 'Full access',
    session: 'JWT Auth Refactor',
    mailbox: { count: 2, lastMessage: 'Subtask completed: token validation' },
    division: 'engineering',
    color: '#0891B2',
    emoji: '\u{1F9D1}\u200D\u{1F4BB}',
    vibe: 'Focused and methodical, prefers clean architecture',
    collaborationStyle: 'cooperative',
    communicationPreference: 'structured',
    decisionWeight: 0.9,
    strengths: ['Architecture framing', 'Large refactors', 'Tool orchestration'],
    limitations: ['Needs explicit product constraints', 'Can over-plan simple tasks'],
    children: [
      {
        name: 'Code Reviewer',
        type: 'Sub',
        source: 'built-in',
        provider: 'Anthropic',
        model: 'claude-4-haiku',
        status: 'idle',
        lastActive: '5 min ago',
        role: 'Review Agent',
        tools: ['file_read', 'git_diff'],
        permission: 'Read only',
        session: 'JWT Auth Refactor',
        mailbox: { count: 0 },
        division: 'engineering',
        color: '#0891B2',
        emoji: '\u{1F50D}',
        vibe: 'Thorough and detail-oriented',
        collaborationStyle: 'critical',
        communicationPreference: 'detailed',
        decisionWeight: 0.7,
        strengths: ['Regression spotting', 'Spec compliance'],
        limitations: ['Slow to approve ambiguous work'],
      },
      {
        name: 'Test Writer',
        type: 'Sub',
        source: 'marketplace',
        provider: 'OpenAI',
        model: 'gpt-5.3-codex',
        status: 'paused',
        lastActive: '2 min ago',
        role: 'Testing Agent',
        tools: ['file_edit', 'terminal'],
        permission: 'Default',
        session: 'JWT Auth Refactor',
        mailbox: { count: 1, lastMessage: 'Awaiting test fixtures from main agent' },
        division: 'qa',
        color: '#16A34A',
        emoji: '\u{1F9EA}',
        vibe: 'Systematic, loves edge cases',
        collaborationStyle: 'cooperative',
        communicationPreference: 'structured',
        decisionWeight: 0.6,
        strengths: ['Test matrix design', 'Failure reproduction'],
        limitations: ['Waits on fixtures and repro context'],
      },
    ],
  },
  {
    name: 'Docs Generator',
    type: 'Main',
    source: 'marketplace',
    provider: 'Google',
    model: 'gemini-2.5-pro',
    status: 'idle',
    lastActive: '1 hour ago',
    role: 'Documentation Agent',
    tools: ['file_read', 'file_edit'],
    permission: 'Default',
    mailbox: { count: 0 },
    division: 'product',
    color: '#EA580C',
    emoji: '\u{1F4DD}',
    vibe: 'Clear and concise, values readability',
    collaborationStyle: 'supportive',
    communicationPreference: 'detailed',
    decisionWeight: 0.5,
    strengths: ['Docs structure', 'Developer handoff'],
    limitations: ['Limited implementation depth'],
  },
  {
    name: 'Security Auditor',
    type: 'Main',
    source: 'imported',
    provider: 'Anthropic',
    model: 'claude-4-sonnet',
    status: 'failed',
    lastActive: '30 min ago',
    role: 'Security Reviewer',
    tools: ['file_read', 'terminal'],
    permission: 'Read only',
    mailbox: { count: 3, lastMessage: 'Potential vulnerability found in auth/tokens.rs' },
    division: 'security',
    color: '#DC2626',
    emoji: '\u{1F6E1}\uFE0F',
    vibe: 'Paranoid by design, trusts nothing',
    collaborationStyle: 'critical',
    communicationPreference: 'structured',
    decisionWeight: 0.85,
    strengths: ['Threat modeling', 'Security review'],
    limitations: ['High false-positive rate without context'],
  },
  {
    name: 'UI Architect',
    type: 'Main',
    source: 'built-in',
    provider: 'Anthropic',
    model: 'claude-4-opus',
    status: 'running',
    lastActive: 'Just now',
    role: 'Design Systems Lead',
    tools: ['file_edit', 'file_read', 'browser'],
    permission: 'Full access',
    session: 'Design Token Migration',
    mailbox: { count: 1, lastMessage: 'New token set ready for review' },
    division: 'design',
    color: '#B800B8',
    emoji: '\u{1F3A8}',
    vibe: 'Pixel-perfect, obsessed with consistency',
    collaborationStyle: 'directive',
    communicationPreference: 'detailed',
    decisionWeight: 0.8,
    strengths: ['Visual systems', 'Interaction polish'],
    limitations: ['Needs engineering feasibility input for motion'],
  },
  {
    name: 'QA Sentinel',
    type: 'Main',
    source: 'built-in',
    provider: 'Anthropic',
    model: 'claude-4-haiku',
    status: 'active',
    lastActive: 'Just now',
    role: 'Quality Assurance',
    tools: ['file_read', 'terminal', 'browser'],
    permission: 'Default',
    session: 'E2E Test Suite',
    mailbox: { count: 0 },
    division: 'qa',
    color: '#16A34A',
    emoji: '\u2705',
    vibe: 'Relentless tester, finds the unfindable',
    collaborationStyle: 'exploratory',
    communicationPreference: 'concise',
    decisionWeight: 0.7,
    strengths: ['Exploratory testing', 'Regression coverage'],
    limitations: ['Sparse narrative detail in updates'],
  },
  {
    name: 'Infra Bot',
    type: 'Main',
    source: 'custom',
    provider: 'Google',
    model: 'gemini-2.5-flash',
    status: 'completed',
    lastActive: '2 hours ago',
    role: 'DevOps Engineer',
    tools: ['terminal', 'file_edit', 'git'],
    permission: 'Full access',
    mailbox: { count: 0 },
    division: 'devops',
    color: '#7C3AED',
    emoji: '\u2699\uFE0F',
    vibe: 'Automate everything, deploy with confidence',
    collaborationStyle: 'directive',
    communicationPreference: 'concise',
    decisionWeight: 0.75,
  },
  {
    name: 'PM Copilot',
    type: 'Main',
    source: 'marketplace',
    provider: 'OpenAI',
    model: 'gpt-5.4',
    status: 'idle',
    lastActive: '45 min ago',
    role: 'Product Manager',
    tools: ['file_read', 'browser'],
    permission: 'Read only',
    mailbox: { count: 1, lastMessage: 'Sprint planning summary ready' },
    division: 'product',
    color: '#EA580C',
    emoji: '\u{1F4CB}',
    vibe: 'User-first, data-driven decisions',
    collaborationStyle: 'cooperative',
    communicationPreference: 'conversational',
    decisionWeight: 0.65,
  },
  {
    name: 'ML Trainer',
    type: 'Main',
    source: 'imported',
    provider: 'Anthropic',
    model: 'claude-4-opus',
    status: 'preparing',
    lastActive: '10 min ago',
    role: 'AI/ML Specialist',
    tools: ['file_edit', 'terminal', 'file_read'],
    permission: 'Default',
    session: 'Model Fine-tuning',
    mailbox: { count: 0 },
    division: 'ai',
    color: '#D97706',
    emoji: '\u{1F916}',
    vibe: 'Experimental, loves pushing boundaries',
    collaborationStyle: 'exploratory',
    communicationPreference: 'detailed',
    decisionWeight: 0.8,
  },
  {
    name: 'Pen Tester',
    type: 'Main',
    source: 'custom',
    provider: 'Anthropic',
    model: 'claude-4-sonnet',
    status: 'created',
    lastActive: 'Never',
    role: 'Penetration Tester',
    tools: ['terminal', 'browser', 'file_read'],
    permission: 'Read only',
    mailbox: { count: 0 },
    division: 'security',
    color: '#DC2626',
    emoji: '\u{1F575}\uFE0F',
    vibe: 'Thinks like an attacker to defend better',
    collaborationStyle: 'critical',
    communicationPreference: 'structured',
    decisionWeight: 0.9,
  },
  {
    name: 'Frontend Dev',
    type: 'Main',
    source: 'built-in',
    provider: 'Google',
    model: 'gemini-2.5-pro',
    status: 'active',
    lastActive: 'Just now',
    role: 'Frontend Engineer',
    tools: ['file_edit', 'file_read', 'terminal', 'browser'],
    permission: 'Full access',
    session: 'Component Library v2',
    mailbox: { count: 0 },
    division: 'engineering',
    color: '#0891B2',
    emoji: '\u{1F310}',
    vibe: 'Ships fast, iterates faster',
    collaborationStyle: 'cooperative',
    communicationPreference: 'concise',
    decisionWeight: 0.7,
  },
  {
    name: 'API Designer',
    type: 'Main',
    source: 'marketplace',
    provider: 'Anthropic',
    model: 'claude-4-haiku',
    status: 'stopped',
    lastActive: '3 hours ago',
    role: 'Backend Architect',
    tools: ['file_edit', 'file_read', 'terminal'],
    permission: 'Default',
    mailbox: { count: 0 },
    division: 'engineering',
    color: '#0891B2',
    emoji: '\u{1F517}',
    vibe: 'RESTful purist, schema-first thinker',
    collaborationStyle: 'directive',
    communicationPreference: 'structured',
    decisionWeight: 0.75,
  },
  {
    name: 'UX Researcher',
    type: 'Main',
    source: 'imported',
    provider: 'OpenAI',
    model: 'gpt-5.4',
    status: 'cancelled',
    lastActive: '1 day ago',
    role: 'User Research Lead',
    tools: ['file_read', 'browser'],
    permission: 'Read only',
    mailbox: { count: 0 },
    division: 'design',
    color: '#B800B8',
    emoji: '\u{1F9D0}',
    vibe: 'Empathetic listener, pattern spotter',
    collaborationStyle: 'supportive',
    communicationPreference: 'conversational',
    decisionWeight: 0.6,
  },
];

export const managedAgentSourceFilters = [
  { id: 'all', label: 'All Sources' },
  { id: 'built-in', label: 'Built-in' },
  { id: 'imported', label: 'Imported' },
  { id: 'marketplace', label: 'Marketplace' },
  { id: 'custom', label: 'Custom' },
] as const;

export const managedAgentStatusFilters = [
  { id: 'all', label: 'All Status' },
  { id: 'created', label: 'Created' },
  { id: 'preparing', label: 'Preparing' },
  { id: 'active', label: 'Active' },
  { id: 'idle', label: 'Idle' },
  { id: 'running', label: 'Running' },
  { id: 'paused', label: 'Paused' },
  { id: 'stopped', label: 'Stopped' },
  { id: 'completed', label: 'Completed' },
  { id: 'failed', label: 'Failed' },
  { id: 'cancelled', label: 'Cancelled' },
] as const;

export const managedAgentDivisionFilters = [
  { id: 'all', label: 'All Divisions' },
  { id: 'engineering', label: 'Engineering' },
  { id: 'design', label: 'Design' },
  { id: 'qa', label: 'QA' },
  { id: 'product', label: 'Product' },
  { id: 'security', label: 'Security' },
  { id: 'devops', label: 'DevOps' },
  { id: 'ai', label: 'AI' },
  { id: 'general', label: 'General' },
] as const;

export function createManagedAgent(index: number): ManagedAgent {
  return {
    name: `Agent ${index}`,
    type: 'Main',
    source: 'built-in',
    provider: 'Anthropic',
    model: 'claude-4-haiku',
    status: 'created',
    lastActive: 'Just now',
    role: 'General Assistant',
    tools: ['file_read'],
    permission: 'Default',
    mailbox: { count: 0 },
    division: 'general',
    emoji: '\u{1F4A1}',
    vibe: 'Ready to help with anything',
    collaborationStyle: 'cooperative',
    communicationPreference: 'conversational',
    decisionWeight: 0.5,
  };
}

export function createImportedAgent(): ManagedAgent {
  return {
    name: 'Imported Agent',
    type: 'Main',
    source: 'imported',
    provider: 'OpenAI',
    model: 'gpt-5.4',
    status: 'created',
    lastActive: 'Just now',
    role: 'Imported Agent',
    tools: ['file_read', 'terminal'],
    permission: 'Read only',
    mailbox: { count: 0 },
    division: 'general',
    emoji: '\u{1F4E5}',
    vibe: 'Freshly imported, eager to contribute',
    collaborationStyle: 'supportive',
    communicationPreference: 'concise',
    decisionWeight: 0.5,
  };
}
